### ISSUE TITLE
Laptop connectivity without Bluetooth dongle

### ISSUE THREAD

**Issue by pbreach** [nataddrho/DigiCue-USB#2]
I'm too familiar serial connections, but do you think it would be possible to connect to a laptop that has built-in Bluetooth connectivity as opposed to using the dongle? If so what do you think would need to be changed?

**Comment by nataddrho** [comment]
I think that this would either be a huge effort to write a library of drivers for all of the different Bluetooth hardware out there, or someone smarter than me software wise knows of an existing platform that we can leverage to do this successfully.
